occupation = {
      "Management in Business, Science, and Arts":[
         "Chief executives and legislators/public administration",
         "General and Operations Managers",
         "Managers in Marketing, Advertising, and Public Relations",
         "Administrative Services Managers",
         "Computer and Information Systems Managers",
         "Financial Managers",
         "Human Resources Managers",
         "Industrial Production Managers",
         "Purchasing Managers",
         "Transportation, Storage, and Distribution Managers",
         "Farmers, Ranchers, and Other Agricultural Managers",
         "Constructions Managers",
         "Education Administrators",
         "Architectural and Engineering Managers",
         "Food Service and Lodging Managers",
         "Funeral Directors",
         "Gaming Managers",
         "Medical and Health Services Managers",
         "Natural Science Managers",
         "Property, Real Estate, and Community Association Managers",
         "Social and Community Service Managers",
         "Managers, nec (including Postmasters)"
      ],
      "Business Operations Specialists":[
         "Agents and Business Managers of Artists, Performers, and Athletes",
         "Buyers and Purchasing Agents, Farm Products",
         "Wholesale and Retail Buyers, Except Farm Products",
         "Purchasing Agents, Except Wholesale, Retail, and Farm Products",
         "Claims Adjusters, Appraisers, Examiners, and Investigators",
         "Compliance Officers, Except Agriculture",
         "Cost Estimators",
         "Human Resources, Training, and Labor Relations Specialists",
         "Logisticians",
         "Management Analysts",
         "Meeting and Convention Planners",
         "Other Business Operations and Management Specialists"
      ],
      "Financial Specialists":[
         "Accountants and Auditors",
         "Appraisers and Assessors of Real Estate",
         "Budget Analysts",
         "Credit Analysts",
         "Financial Analysts",
         "Personal Financial Advisors",
         "Insurance Underwriters",
         "Financial Examiners",
         "Credit Counselors and Loan Officers",
         "Tax Examiners and Collectors, and Revenue Agents",
         "Tax Preparers",
         "Financial Specialists, nec"
      ],
      "Computer and Mathematical":[
         "Computer Scientists and Systems Analysts/Network systems Analysts/Web Developers",
         "Computer Programmers",
         "Software Developers, Applications and Systems Software",
         "Computer Support Specialists",
         "Database Administrators",
         "Network and Computer Systems Administrators",
         "Actuaries",
         "Operations Research Analysts",
         "Statisticians",
         "Mathematical science occupations, nec"
      ],
      "Architecture and Engineering":[
         "Architects, Except Naval",
         "Surveyors, Cartographers, and Photogrammetrists",
         "Aerospace Engineers",
         "Chemical Engineers",
         "Civil Engineers",
         "Computer Hardware Engineers",
         "Electrical and Electronics Engineers",
         "Environmental Engineers",
         "Industrial Engineers, including Health and Safety",
         "Marine Engineers and Naval Architects",
         "Materials Engineers",
         "Mechanical Engineers",
         "Petroleum, mining and geological engineers, including mining safety engineers",
         "Engineers, nec",
         "Drafters"
      ],
      "Technicians":[
         "Engineering Technicians, Except Drafters",
         "Surveying and Mapping Technicians"
      ],
      "Life, Physical, and Social Science":[
         "Agricultural and Food Scientists",
         "Biological Scientists",
         "Conservation Scientists and Foresters",
         "Medical Scientists, and Life Scientists, All Other",
         "Astronomers and Physicists",
         "Atmospheric and Space Scientists",
         "Chemists and Materials Scientists",
         "Environmental Scientists and Geoscientists",
         "Physical Scientists, nec",
         "Economists and market researchers",
         "Psychologists",
         "Urban and Regional Planners",
         "Social Scientists, nec",
         "Agricultural and Food Science Technicians",
         "Biological Technicians",
         "Chemical Technicians",
         "Geological and Petroleum Technicians, and Nuclear Technicians",
         "Life, Physical, and Social Science Technicians, nec",
         "Professional, Research, or Technical Workers, nec"
      ],
      "Community and Social Services":[
         "Counselors",
         "Social Workers",
         "Community and Social Service Specialists, nec",
         "Clergy",
         "Directors, Religious Activities and Education",
         "Religious Workers, nec"
      ],
      "Legal":[
         "Lawyers, and judges, magistrates, and other judicial workers",
         "Paralegals and Legal Assistants",
         "Legal Support Workers, nec"
      ],
      "Education, Training, and Library":[
         "Postsecondary Teachers",
         "Preschool and Kindergarten Teachers",
         "Elementary and Middle School Teachers",
         "Secondary School Teachers",
         "Special Education Teachers",
         "Other Teachers and Instructors",
         "Archivists, Curators, and Museum Technicians",
         "Librarians",
         "Library Technicians",
         "Teacher Assistants",
         "Education, Training, and Library Workers, nec"
      ],
      "Arts, Design, Entertainment, Sports, and Media":[
         "Artists and Related Workers",
         "Designers",
         "Actors, Producers, and Directors",
         "Athletes, Coaches, Umpires, and Related Workers",
         "Dancers and Choreographers",
         "Musicians, Singers, and Related Workers",
         "Entertainers and Performers, Sports and Related Workers, All Other",
         "Announcers",
         "Editors, News Analysts, Reporters, and Correspondents",
         "Public Relations Specialists",
         "Technical Writers",
         "Writers and Authors",
         "Media and Communication Workers, nec",
         "Broadcast and Sound Engineering Technicians and Radio Operators, and media and communication equipment workers, all other",
         "Photographers",
         "Television, Video, and Motion Picture Camera Operators and Editors"
      ],
      "Healthcare Practitioners and Technicians":[
         "Chiropractors",
         "Dentists",
         "Dieticians and Nutritionists",
         "Optometrists",
         "Pharmacists",
         "Physicians and Surgeons",
         "Physician Assistants",
         "Podiatrists",
         "Registered Nurses",
         "Audiologists",
         "Occupational Therapists",
         "Physical Therapists",
         "Radiation Therapists",
         "Recreational Therapists",
         "Respiratory Therapists",
         "Speech Language Pathologists",
         "Therapists, nec",
         "Veterinarians",
         "Health Diagnosing and Treating Practitioners, nec",
         "Clinical Laboratory Technologists and Technicians",
         "Dental Hygienists",
         "Diagnostic Related Technologists and Technicians",
         "Emergency Medical Technicians and Paramedics",
         "Health Diagnosing and Treating Practitioner Support Technicians",
         "Licensed Practical and Licensed Vocational Nurses",
         "Medical Records and Health Information Technicians",
         "Opticians, Dispensing",
         "Health Technologists and Technicians, nec",
         "Healthcare Practitioners and Technical Occupations, nec"
      ],
      "Healthcare Support":[
         "Nursing, Psychiatric, and Home Health Aides",
         "Occupational Therapy Assistants and Aides",
         "Physical Therapist Assistants and Aides",
         "Massage Therapists",
         "Dental Assistants",
         "Medical Assistants and Other Healthcare Support Occupations, nec"
      ],
      "Protective Service":[
         "First-Line Supervisors of Correctional Officers",
         "First-Line Supervisors of Police and Detectives",
         "First-Line Supervisors of Fire Fighting and Prevention Workers",
         "Supervisors, Protective Service Workers, All Other",
         "Firefighters",
         "Fire Inspectors",
         "Sheriffs, Bailiffs, Correctional Officers, and Jailers",
         "Police Officers and Detectives",
         "Animal Control",
         "Private Detectives and Investigators",
         "Security Guards and Gaming Surveillance Officers",
         "Crossing Guards",
         "Law enforcement workers, nec"
      ],
      "Food Preparation and Serving":[
         "Chefs and Cooks",
         "First-Line Supervisors of Food Preparation and Serving Workers",
         "Food Preparation Workers",
         "Bartenders",
         "Combined Food Preparation and Serving Workers, Including Fast Food",
         "Counter Attendant, Cafeteria, Food Concession, and Coffee Shop",
         "Waiters and Waitresses",
         "Food Servers, Nonrestaurant",
         "Food preparation and serving related workers, nec",
         "Dishwashers",
         "Host and Hostesses, Restaurant, Lounge, and Coffee Shop"
      ],
      "Building and Grounds Cleaning and Maintenance":[
         "First-Line Supervisors of Housekeeping and Janitorial Workers",
         "First-Line Supervisors of Landscaping, Lawn Service, and Groundskeeping Workers",
         "Janitors and Building Cleaners",
         "Maids and Housekeeping Cleaners",
         "Pest Control Workers",
         "Grounds Maintenance Workers"
      ],
      "Personal Care and Service":[
         "First-Line Supervisors of Gaming Workers",
         "First-Line Supervisors of Personal Service Workers",
         "Animal Trainers",
         "Nonfarm Animal Caretakers",
         "Gaming Services Workers",
         "Ushers, Lobby Attendants, and Ticket Takers",
         "Entertainment Attendants and Related Workers, nec",
         "Funeral Service Workers and Embalmers",
         "Barbers",
         "Hairdressers, Hairstylists, and Cosmetologists",
         "Personal Appearance Workers, nec",
         "Baggage Porters, Bellhops, and Concierges",
         "Tour and Travel Guides",
         "Childcare Workers",
         "Personal Care Aides",
         "Recreation and Fitness Workers",
         "Residential Advisors",
         "Personal Care and Service Workers, All Other"
      ],
      "Sales and Related":[
         "First-Line Supervisors of Sales Workers",
         "Cashiers",
         "Counter and Rental Clerks",
         "Parts Salespersons",
         "Retail Salespersons",
         "Advertising Sales Agents",
         "Insurance Sales Agents",
         "Securities, Commodities, and Financial Services Sales Agents",
         "Travel Agents",
         "Sales Representatives, Services, All Other",
         "Sales Representatives, Wholesale and Manufacturing",
         "Models, Demonstrators, and Product Promoters",
         "Real Estate Brokers and Sales Agents",
         "Sales Engineers",
         "Telemarketers",
         "Door-to-Door Sales Workers, News and Street Vendors, and Related Workers",
         "Sales and Related Workers, All Other"
      ],
      "Office and Administrative Support":[
         "First-Line Supervisors of Office and Administrative Support Workers",
         "Switchboard Operators, Including Answering Service",
         "Telephone Operators",
         "Communications Equipment Operators, All Other",
         "Bill and Account Collectors",
         "Billing and Posting Clerks",
         "Bookkeeping, Accounting, and Auditing Clerks",
         "Gaming Cage Workers",
         "Payroll and Timekeeping Clerks",
         "Procurement Clerks",
         "Bank Tellers",
         "Financial Clerks, nec",
         "Brokerage Clerks",
         "Court, Municipal, and License Clerks",
         "Credit Authorizers, Checkers, and Clerks",
         "Customer Service Representatives",
         "Eligibility Interviewers, Government Programs",
         "File Clerks",
         "Hotel, Motel, and Resort Desk Clerks",
         "Interviewers, Except Eligibility and Loan",
         "Library Assistants, Clerical",
         "Loan Interviewers and Clerks",
         "New Account Clerks",
         "Correspondent clerks and order clerks",
         "Human Resources Assistants, Except Payroll and Timekeeping",
         "Receptionists and Information Clerks",
         "Reservation and Transportation Ticket Agents and Travel Clerks",
         "Information and Record Clerks, All Other",
         "Cargo and Freight Agents",
         "Couriers and Messengers",
         "Dispatchers",
         "Meter Readers, Utilities",
         "Postal Service Clerks",
         "Postal Service Mail Carriers",
         "Postal Service Mail Sorters, Processors, and Processing Machine Operators",
         "Production, Planning, and Expediting Clerks",
         "Shipping, Receiving, and Traffic Clerks",
         "Stock Clerks and Order Fillers",
         "Weighers, Measurers, Checkers, and Samplers, Recordkeeping",
         "Secretaries and Administrative Assistants",
         "Computer Operators",
         "Data Entry Keyers",
         "Word Processors and Typists",
         "Insurance Claims and Policy Processing Clerks",
         "Mail Clerks and Mail Machine Operators, Except Postal Service",
         "Office Clerks, General",
         "Office Machine Operators, Except Computer",
         "Proofreaders and Copy Markers",
         "Statistical Assistants",
         "Office and administrative support workers, nec"
      ],
      "Farming, Fisheries, and Forestry":[
         "First-Line Supervisors of Farming, Fishing, and Forestry Workers",
         "Agricultural Inspectors",
         "Graders and Sorters, Agricultural Products",
         "Agricultural workers, nec",
         "Fishing and hunting workers",
         "Forest and Conservation Workers",
         "Logging Workers"
      ],
      "Construction":[
         "First-Line Supervisors of Construction Trades and Extraction Workers",
         "Boilermakers",
         "Brickmasons, Blockmasons, and Stonemasons",
         "Carpenters",
         "Carpet, Floor, and Tile Installers and Finishers",
         "Cement Masons, Concrete Finishers, and Terrazzo Workers",
         "Construction Laborers",
         "Paving, Surfacing, and Tamping Equipment Operators",
         "Construction equipment operators except paving, surfacing, and tamping equipment operators",
         "Drywall Installers, Ceiling Tile Installers, and Tapers",
         "Electricians",
         "Glaziers",
         "Insulation Workers",
         "Painters, Construction and Maintenance",
         "Paperhangers",
         "Pipelayers, Plumbers, Pipefitters, and Steamfitters",
         "Plasterers and Stucco Masons",
         "Reinforcing Iron and Rebar Workers",
         "Roofers",
         "Sheet Metal Workers, metal-working",
         "Structural Iron and Steel Workers",
         "Helpers, Construction Trades",
         "Construction and Building Inspectors",
         "Elevator Installers and Repairers",
         "Fence Erectors",
         "Hazardous Materials Removal Workers",
         "Highway Maintenance Workers",
         "Rail-Track Laying and Maintenance Equipment Operators",
         "Construction workers, nec"
      ],
      "Extraction":[
         "Derrick, rotary drill, and service unit operators, and roustabouts, oil, gas, and mining",
         "Earth Drillers, Except Oil and Gas",
         "Explosives Workers, Ordnance Handling Experts, and Blasters",
         "Mining Machine Operators",
         "Extraction workers, nec"
      ],
      "Installation, Maintenance, and Repair":[
         "First-Line Supervisors of Mechanics, Installers, and Repairers",
         "Computer, Automated Teller, and Office Machine Repairers",
         "Radio and Telecommunications Equipment Installers and Repairers",
         "Avionics Technicians",
         "Electric Motor, Power Tool, and Related Repairers",
         "Electrical and electronics repairers, transportation equipment, and industrial and utility",
         "Electronic Equipment Installers and Repairers, Motor Vehicles",
         "Electronic Home Entertainment Equipment Installers and Repairers",
         "Electronic Repairs, nec",
         "Security and Fire Alarm Systems Installers",
         "Aircraft Mechanics and Service Technicians",
         "Automotive Body and Related Repairers",
         "Automotive Glass Installers and Repairers",
         "Automotive Service Technicians and Mechanics",
         "Bus and Truck Mechanics and Diesel Engine Specialists",
         "Heavy Vehicle and Mobile Equipment Service Technicians and Mechanics",
         "Small Engine Mechanics",
         "Vehicle and Mobile Equipment Mechanics, Installers, and Repairers, nec",
         "Control and Valve Installers and Repairers",
         "Heating, Air Conditioning, and Refrigeration Mechanics and Installers",
         "Home Appliance Repairers",
         "Industrial and Refractory Machinery Mechanics",
         "Maintenance and Repair Workers, General",
         "Maintenance Workers, Machinery",
         "Millwrights",
         "Electrical Power-Line Installers and Repairers",
         "Telecommunications Line Installers and Repairers",
         "Precision Instrument and Equipment Repairers",
         "Coin, Vending, and Amusement Machine Servicers and Repairers",
         "Locksmiths and Safe Repairers",
         "Manufactured Building and Mobile Home Installers",
         "Riggers",
         "Helpers--Installation, Maintenance, and Repair Workers",
         "Other Installation, Maintenance, and Repair Workers Including Wind Turbine Service Technicians, and Commercial Divers, and Signal and Track Switch Repairers"
      ],
      "Production":[
         "First-Line Supervisors of Production and Operating Workers",
         "Aircraft Structure, Surfaces, Rigging, and Systems Assemblers",
         "Electrical, Electronics, and Electromechanical Assemblers",
         "Engine and Other Machine Assemblers",
         "Structural Metal Fabricators and Fitters",
         "Assemblers and Fabricators, nec",
         "Bakers",
         "Butchers and Other Meat, Poultry, and Fish Processing Workers",
         "Food and Tobacco Roasting, Baking, and Drying Machine Operators and Tenders",
         "Food Batchmakers",
         "Food Cooking Machine Operators and Tenders",
         "Food Processing, nec",
         "Computer Control Programmers and Operators",
         "Extruding and Drawing Machine Setters, Operators, and Tenders, Metal and Plastic",
         "Forging Machine Setters, Operators, and Tenders, Metal and Plastic",
         "Rolling Machine Setters, Operators, and Tenders, metal and Plastic",
         "Cutting, Punching, and Press Machine Setters, Operators, and Tenders, Metal and Plastic",
         "Drilling and Boring Machine Tool Setters, Operators, and Tenders, Metal and Plastic",
         "Grinding, Lapping, Polishing, and Buffing Machine Tool Setters, Operators, and Tenders, Metal and Plastic",
         "Lathe and Turning Machine Tool Setters, Operators, and Tenders, Metal and Plastic",
         "Machinists",
         "Metal Furnace Operators, Tenders, Pourers, and Casters",
         "Model Makers and Patternmakers, Metal and Plastic",
         "Molders and Molding Machine Setters, Operators, and Tenders, Metal and Plastic",
         "Tool and Die Makers",
         "Welding, Soldering, and Brazing Workers",
         "Heat Treating Equipment Setters, Operators, and Tenders, Metal and Plastic",
         "Plating and Coating Machine Setters, Operators, and Tenders, Metal and Plastic",
         "Tool Grinders, Filers, and Sharpeners",
         "Metal workers and plastic workers, nec",
         "Bookbinders, Printing Machine Operators, and Job Printers",
         "Prepress Technicians and Workers",
         "Laundry and Dry-Cleaning Workers",
         "Pressers, Textile, Garment, and Related Materials",
         "Sewing Machine Operators",
         "Shoe and Leather Workers and Repairers",
         "Shoe Machine Operators and Tenders",
         "Tailors, Dressmakers, and Sewers",
         "Textile bleaching and dyeing, and cutting machine setters, operators, and tenders",
         "Textile Knitting and Weaving Machine Setters, Operators, and Tenders",
         "Textile Winding, Twisting, and Drawing Out Machine Setters, Operators, and Tenders",
         "Upholsterers",
         "Textile, Apparel, and Furnishings workers, nec",
         "Cabinetmakers and Bench Carpenters",
         "Furniture Finishers",
         "Sawing Machine Setters, Operators, and Tenders, Wood",
         "Woodworking Machine Setters, Operators, and Tenders, Except Sawing",
         "Woodworkers including model makers and patternmakers, nec",
         "Power Plant Operators, Distributors, and Dispatchers",
         "Stationary Engineers and Boiler Operators",
         "Water Wastewater Treatment Plant and System Operators",
         "Plant and System Operators, nec",
         "Chemical Processing Machine Setters, Operators, and Tenders",
         "Crushing, Grinding, Polishing, Mixing, and Blending Workers",
         "Cutting Workers",
         "Extruding, Forming, Pressing, and Compacting Machine Setters, Operators, and Tenders",
         "Furnace, Kiln, Oven, Drier, and Kettle Operators and Tenders",
         "Inspectors, Testers, Sorters, Samplers, and Weighers",
         "Jewelers and Precious Stone and Metal Workers",
         "Medical, Dental, and Ophthalmic Laboratory Technicians",
         "Packaging and Filling Machine Operators and Tenders",
         "Painting Workers and Dyers",
         "Photographic Process Workers and Processing Machine Operators",
         "Adhesive Bonding Machine Operators and Tenders",
         "Cleaning, Washing, and Metal Pickling Equipment Operators and Tenders",
         "Etchers, Engravers, and Lithographers",
         "Molders, Shapers, and Casters, Except Metal and Plastic",
         "Paper Goods Machine Setters, Operators, and Tenders",
         "Tire Builders",
         "Helpers--Production Workers",
         "Other production workers including semiconductor processors and cooling and freezing equipment operators"
      ],
      "Transportation and Material Moving":[
         "Supervisors of Transportation and Material Moving Workers",
         "Aircraft Pilots and Flight Engineers",
         "Air Traffic Controllers and Airfield Operations Specialists",
         "Flight Attendants and Transportation Workers and Attendants",
         "Bus and Ambulance Drivers and Attendants",
         "Driver/Sales Workers and Truck Drivers",
         "Taxi Drivers and Chauffeurs",
         "Motor Vehicle Operators, All Other",
         "Locomotive Engineers and Operators",
         "Railroad Brake, Signal, and Switch Operators",
         "Railroad Conductors and Yardmasters",
         "Subway, Streetcar, and Other Rail Transportation Workers",
         "Sailors and marine oilers, and ship engineers",
         "Ship and Boat Captains and Operators",
         "Parking Lot Attendants",
         "Automotive and Watercraft Service Attendants",
         "Transportation Inspectors",
         "Transportation workers, nec",
         "Crane and Tower Operators",
         "Dredge, Excavating, and Loading Machine Operators",
         "Conveyor operators and tenders, and hoist and winch operators",
         "Industrial Truck and Tractor Operators",
         "Cleaners of Vehicles and Equipment",
         "Laborers and Freight, Stock, and Material Movers, Hand",
         "Machine Feeders and Offbearers",
         "Packers and Packagers, Hand",
         "Pumping Station Operators",
         "Refuse and Recyclable Material Collectors",
         "Material moving workers, nec"
      ],
      "Military":[
         "Military Officer Special and Tactical Operations Leaders",
         "First-Line Enlisted Military Supervisors",
         "Military Enlisted Tactical Operations and Air/Weapons Specialists and Crew Members",
         "Military, Rank Not Specified"
      ],
      "No Occupation":[
         "Unemployed, with No Work Experience in the Last 5 Years or Earlier or Never Worked"
      ]
   }
